### ISSUE TITLE
Invalid example value for Patch An Existing Item endpoint documentation

### ISSUE THREAD

**Issue by nroylance-lucid** [airfocusio/airfocus-api#1]
I was looking at the documentation for the endpoint to patch an existing item (`/api/workspaces/{workspaceId}/items/{itemId}`) and it gives an example request body value of:
```
{
  "ops": [
    ...
  ]
}
```
Trying that format of request body failed for me, but succeeded with:
```
[
  ...
]
```

It looks like the endpoint is expecting just an array of patch operations, not an object holding an array in the "ops" field, but the documentation doesn't reflect that.

Let me know if I can help or provide more details.

**Comment by choffmeister** [comment]
Hii @nroylance-lucid. Thanks for bringing this up. This seems to be wrong for all patch operations. We will look into that and fix it.

**Comment by choffmeister** [comment]
Should be fixed with f1c292bd6f66a94aef2595b506d4c3d8cdb31c72
